// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"go-feature-based-boilerplate/infrastructure/config"
	"go-feature-based-boilerplate/infrastructure/database/postgres"
	"go-feature-based-boilerplate/infrastructure/telemetry"
	"go-feature-based-boilerplate/internal/auth"
	handler2 "go-feature-based-boilerplate/internal/auth/handler"
	postgres3 "go-feature-based-boilerplate/internal/auth/repository/postgres"
	usecase2 "go-feature-based-boilerplate/internal/auth/usecase"
	validator2 "go-feature-based-boilerplate/internal/auth/validator"
	"go-feature-based-boilerplate/internal/health/checker"
	handler3 "go-feature-based-boilerplate/internal/health/handler"
	"go-feature-based-boilerplate/internal/user/handler"
	postgres2 "go-feature-based-boilerplate/internal/user/repository/postgres"
	"go-feature-based-boilerplate/internal/user/usecase"
	"go-feature-based-boilerplate/internal/user/validator"
)

// Injectors from wire.go:

// InitializeApp is the Wire injection entry point.
// wire.Build declares the full dependency graph; wire generates wire_gen.go.
func InitializeApp(ctx context.Context) (*App, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	zapLogger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	db, err := postgres.New(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := postgres2.NewUserRepository(db)
	validatorValidator := validator.New()
	createUsecase := usecase.NewCreateUsecase(userRepository, validatorValidator)
	findUsecase := usecase.NewFindUsecase(userRepository)
	updateUsecase := usecase.NewUpdateUsecase(userRepository, validatorValidator)
	deleteUsecase := usecase.NewDeleteUsecase(userRepository)
	handlerHandler := handler.NewHandler(createUsecase, findUsecase, updateUsecase, deleteUsecase)
	authRepository := postgres3.NewAuthRepository(db)
	userProvider := auth.ProvideUserProvider(userRepository)
	validator3 := validator2.New()
	tokenConfig := usecase2.NewTokenConfig(configConfig)
	loginUsecase := usecase2.NewLoginUsecase(authRepository, userProvider, validator3, tokenConfig)
	refreshUsecase := usecase2.NewRefreshUsecase(authRepository, userProvider, validator3, tokenConfig)
	logoutUsecase := usecase2.NewLogoutUsecase(authRepository, validator3)
	handler4 := handler2.NewHandler(loginUsecase, refreshUsecase, logoutUsecase)
	dbPinger := checker.NewDBPinger(db)
	handler5 := handler3.NewHandler(dbPinger)
	server := NewGRPCServer(configConfig, zapLogger, handlerHandler, handler4, handler5)
	httpServer, err := NewHTTPGateway(ctx, configConfig)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider, err := telemetry.NewTracerFromConfig(ctx, configConfig)
	if err != nil {
		return nil, nil, err
	}
	meterProvider, err := telemetry.NewMeterFromConfig(configConfig)
	if err != nil {
		return nil, nil, err
	}
	app := NewApp(configConfig, zapLogger, db, server, httpServer, tracerProvider, meterProvider)
	return app, func() {
	}, nil
}
